name: My Target Workflow

on:
  repository_dispatch:
    types: [trigger-workflow]
    
jobs:
  build:
    runs-on: [ oci-runner ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.sha }}
    
      - name: Run a script
        run: |
          echo "Hello, world!"
